// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWNb-FMCTDemT0v4ZaAalbTbpRP11QUBE',
    appId: '1:147475777798:web:040ce3ad58931f12727687',
    messagingSenderId: '147475777798',
    projectId: 'chat-app01-27028',
    authDomain: 'chat-app01-27028.firebaseapp.com',
    storageBucket: 'chat-app01-27028.firebasestorage.app',
    measurementId: 'G-5L7LQF3G9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmuj2mGzt2kCg_4rjB3WyG_B46-7qPrx4',
    appId: '1:147475777798:android:ba587673cdcef09a727687',
    messagingSenderId: '147475777798',
    projectId: 'chat-app01-27028',
    storageBucket: 'chat-app01-27028.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm4I_hoUTv88PHsVnMgnY6e5MwmJeo0pY',
    appId: '1:147475777798:ios:35d7a1f243760841727687',
    messagingSenderId: '147475777798',
    projectId: 'chat-app01-27028',
    storageBucket: 'chat-app01-27028.firebasestorage.app',
    iosBundleId: 'com.example.chat01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWNb-FMCTDemT0v4ZaAalbTbpRP11QUBE',
    appId: '1:147475777798:web:0347959d001fa474727687',
    messagingSenderId: '147475777798',
    projectId: 'chat-app01-27028',
    authDomain: 'chat-app01-27028.firebaseapp.com',
    storageBucket: 'chat-app01-27028.firebasestorage.app',
    measurementId: 'G-CKCW7ZK542',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm4I_hoUTv88PHsVnMgnY6e5MwmJeo0pY',
    appId: '1:147475777798:ios:35d7a1f243760841727687',
    messagingSenderId: '147475777798',
    projectId: 'chat-app01-27028',
    storageBucket: 'chat-app01-27028.firebasestorage.app',
    iosBundleId: 'com.example.chat01',
  );

}